### 🔍 Obtener datos desde la hoja "Results" (fija en backend)
GET http://localhost:8000/peques/from-sheet
Accept: application/json


### Registrar un nuevo peque (comercio)
POST http://localhost:8000/peques/registrar
Content-Type: application/json

{
  "nombre": "Mi Restaurante de Prueba",
  "ubicacion": "-16.5206962,-68.2064785",
  "correo": "miemail@ejemplo.com",
  "whatsapp": "+59177777777",
  "tipo_negocio": "restaurante"
}
