### 🔍 Obtener datos desde la hoja "Results" (fija en backend)
GET https://serpapi.com/search.json?engine=google_maps&google_domain=google.com&hl=en&place_id=ChIJC5i7REnh8ZMRSUUZwe5BbG8&api_key=d438f066067aa4d0dc9da4415441d6fd9b99ee307cec2f6ed1cea2db3e823096
Accept: application/json
